=== kenwebb/Xholon/Xholon/dtd/MembraneComputing.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Mechanism: Membrane Computing
	MembraneComputing.dtd
	Xholon Project www.primordion.com/Xholon
	March 28, 2006
-->
<!-- Specific Objects may have a multiplicity attribute. -->
<!ENTITY % mult_attr "multiplicity CDATA #REQUIRED">

<!ELEMENT CompletionDetector EMPTY>
<!ELEMENT Environment (Objects)>
<!ELEMENT Membrane (Region,Membrane*)>
<!ATTLIST Membrane roleName NMTOKEN #REQUIRED>
<!ELEMENT Objects ANY>
<!ELEMENT Region (Objects,RuleSet)>
<!ELEMENT RuleSet ANY>
<!ATTLIST RuleSet roleName CDATA #REQUIRED>
<!ELEMENT SuperCell (CompletionDetector,Environment,Membrane)>
<!ELEMENT attribute EMPTY>
<!ATTLIST attribute name NMTOKEN #REQUIRED value NMTOKEN #REQUIRED>

<!-- specific Objects -->
	<!ELEMENT a EMPTY>
	<!ELEMENT b EMPTY>
	<!ELEMENT c EMPTY>
	<!ELEMENT d EMPTY>
	<!ELEMENT e EMPTY>
	<!ELEMENT f EMPTY>
	<!ELEMENT g EMPTY>
	<!ELEMENT h EMPTY>
	<!ELEMENT i EMPTY>
	<!ELEMENT j EMPTY>
	<!ELEMENT k EMPTY>
	<!ELEMENT l EMPTY>
	<!ELEMENT m EMPTY>
	<!ELEMENT n EMPTY>
	<!ELEMENT o EMPTY>
	<!ELEMENT p EMPTY>
	<!ELEMENT q EMPTY>
	<!ELEMENT r EMPTY>
	<!ELEMENT s EMPTY>
	<!ELEMENT t EMPTY>
	<!ELEMENT u EMPTY>
	<!ELEMENT v EMPTY>
	<!ELEMENT w EMPTY>
	<!ELEMENT x EMPTY>
	<!ELEMENT y EMPTY>
	<!ELEMENT z EMPTY>
	<!ELEMENT _ EMPTY>

<!-- specific Rules -->
	<!ELEMENT R1r1 (attribute?)> <!-- RuleSet R1 -->
	<!ELEMENT R1r2 (attribute?)>
	<!ELEMENT R1r3 (attribute?)>
	<!ELEMENT R1r4 (attribute?)>
	<!ELEMENT R1r5 (attribute?)>
	<!ELEMENT R1r6 (attribute?)>
	<!ELEMENT R1r7 (attribute?)>
	<!ELEMENT R1r8 (attribute?)>
	<!ELEMENT R1r9 (attribute?)>
	<!ELEMENT R1r10 (attribute?)>
	<!ELEMENT R2r1 (attribute?)> <!-- RuleSet R2 -->
	<!ELEMENT R2r2 (attribute?)>
	<!ELEMENT R2r3 (attribute?)>
	<!ELEMENT R2r4 (attribute?)>
	<!ELEMENT R2r5 (attribute?)>
	<!ELEMENT R2r6 (attribute?)>
	<!ELEMENT R2r7 (attribute?)>
	<!ELEMENT R2r8 (attribute?)>
	<!ELEMENT R2r9 (attribute?)>
	<!ELEMENT R2r10 (attribute?)>
	<!ELEMENT R3r1 (attribute?)> <!-- RuleSet R3 -->
	<!ELEMENT R3r2 (attribute?)>
	<!ELEMENT R3r3 (attribute?)>
	<!ELEMENT R3r4 (attribute?)>
	<!ELEMENT R3r5 (attribute?)>
	<!ELEMENT R3r6 (attribute?)>
	<!ELEMENT R3r7 (attribute?)>
	<!ELEMENT R3r8 (attribute?)>
	<!ELEMENT R3r9 (attribute?)>
	<!ELEMENT R3r10 (attribute?)>
	<!ELEMENT R4r1 (attribute?)> <!-- RuleSet R4 -->
	<!ELEMENT R4r2 (attribute?)>
	<!ELEMENT R4r3 (attribute?)>
	<!ELEMENT R4r4 (attribute?)>
	<!ELEMENT R4r5 (attribute?)>
	<!ELEMENT R4r6 (attribute?)>
	<!ELEMENT R4r7 (attribute?)>
	<!ELEMENT R4r8 (attribute?)>
	<!ELEMENT R4r9 (attribute?)>
	<!ELEMENT R4r10 (attribute?)>
	<!ELEMENT R5r1 (attribute?)> <!-- RuleSet R5 -->
	<!ELEMENT R5r2 (attribute?)>
	<!ELEMENT R5r3 (attribute?)>
	<!ELEMENT R5r4 (attribute?)>
	<!ELEMENT R5r5 (attribute?)>
	<!ELEMENT R5r6 (attribute?)>
	<!ELEMENT R5r7 (attribute?)>
	<!ELEMENT R5r8 (attribute?)>
	<!ELEMENT R5r9 (attribute?)>
	<!ELEMENT R5r10 (attribute?)>

=== kenwebb/Xholon/Xholon/dtd/examples/MembraneComputing/CoopSys02ex343_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE SuperCell SYSTEM "../../MembraneComputing.dtd"[
	<!-- Objects -->
	<!ATTLIST a multiplicity CDATA #REQUIRED>
	<!ATTLIST c multiplicity CDATA #REQUIRED>
	]>

<!-- CoopSys02ex343_2
-->

<SuperCell>
	<CompletionDetector/>
	<!-- mu=[1[2]2[3]3]1 -->
	<Environment>
		<Objects>
		</Objects>
	</Environment>
    <Membrane roleName="1">
		<Region>
			<Objects>
			</Objects>
			<RuleSet roleName="R1">
				<R1r1/>
				<R1r2><attribute name="priority" value="99"/></R1r2>
			</RuleSet>
		</Region>
		<Membrane roleName="2">
			<Region>
				<Objects>
					<a multiplicity="52"/> <!-- multiplicity value is "n" -->
					<c multiplicity="13"/> <!-- multiplicity value is "k" -->
					<d/>
				</Objects>
				<RuleSet roleName="R2">
					<R2r1/>
					<R2r2/>
					<R2r3><attribute name="priority" value="99"/></R2r3>
				</RuleSet>
			</Region>
		</Membrane>
		<Membrane roleName="3">
			<Region>
				<Objects>
				</Objects>
				<RuleSet roleName="R3">
				</RuleSet>
			</Region>
		</Membrane>
	</Membrane>
</SuperCell>
