=== kenwebb/Xholon/Xholon/dtd/StateMachine_SCXML.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	State Chart XML (SCXML) DTD - from W3C Working Draft 21 February 2007
	http://www.w3.org/TR/scxml/
	This is only the portion of SCXML that is relevant to Xholon.
	This DTD contains some Xholon extensions.
	This DTD is based on the xsd Schema included in the W3C document.
	It can be used to validate SCXML files generated by Xholon.
	Some examples are included with the Xholon distribution,
	in examples/StateMachine_SCXML.
-->

<!-- Basic State Notation -->

<!-- scxml -->
<!ELEMENT scxml (notes*,state*,parallel*,final*)>
<!ATTLIST scxml
	initialstate IDREF #REQUIRED
	xmlns CDATA #IMPLIED
	version NMTOKEN #FIXED "1.0">

<!-- state -->
<!ELEMENT state (onentry?,onexit?,transition*,initial?,state*,parallel*,final*,history*,choice?,doactivity?)>
<!ATTLIST state
	id ID #REQUIRED>

<!-- transition -->
<!-- activity is a Xholon extension -->
<!ELEMENT transition EMPTY> <!-- contains executable content -->
<!ATTLIST transition
	event NMTOKEN #IMPLIED
	cond NMTOKEN #IMPLIED
	activity NMTOKEN #IMPLIED
	target IDREF #IMPLIED>

<!-- parallel -->
<!ELEMENT parallel (onentry?,onexit?,state*,parallel*,history*)>
<!ATTLIST parallel
	id ID #REQUIRED>

<!-- final -->
<!ELEMENT final EMPTY>
<!ATTLIST final
	id ID #REQUIRED>

<!-- onentry -->
<!-- activity is a Xholon extension -->
<!ELEMENT onentry EMPTY> <!-- contains executable content -->
<!ATTLIST onentry
	activity NMTOKEN #IMPLIED>

<!-- onexit -->
<!-- activity is a Xholon extension -->
<!ELEMENT onexit EMPTY> <!-- contains executable content -->
<!ATTLIST onexit
	activity NMTOKEN #IMPLIED>

<!-- Pseudo-States -->

<!-- initial -->
<!ELEMENT initial (transition)>
<!ATTLIST initial
	id ID #IMPLIED>

<!-- history -->
<!ELEMENT history (transition)>
<!ATTLIST history
	id ID #REQUIRED
	type NMTOKEN #IMPLIED>

<!-- Xholon extensions -->

<!-- choice -->
<!ELEMENT choice (transition+)>
<!ATTLIST choice
	id ID #REQUIRED>

<!-- doactivity -->
<!ELEMENT doactivity EMPTY>
<!ATTLIST doactivity
	activity NMTOKEN #IMPLIED>

<!-- non-SCXML comments -->
<!ELEMENT notes (body)>
<!ELEMENT body (p)>
<!ATTLIST body xmlns CDATA #REQUIRED>
<!ELEMENT p (#PCDATA)>

=== kenwebb/Xholon/Xholon/dtd/examples/StateMachine_SCXML/ScxmlModelTest_TestFsm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scxml SYSTEM "../../StateMachine_SCXML.dtd">
<!--
Automatically generated by Xholon version 0.5, using Xholon2Scxml.java
Sun Feb 18 19:46:45 EST 2007
www.primordion.com/Xholon
-->
<scxml xmlns="http://www.w3.org/2005/07/scxml" version="1.0" initialstate="Top">
	<notes>
		<body xmlns="http://www.w3.org/1999/xhtml">
			<p>This SCXML file has been generated by an early version of the Xholon SCXML
				exporter. </p>
		</body>
	</notes>
	
	<!-- States -->
	<state id="Top">
		<initial>
			<transition target="StateA1"/>
		</initial>
		<state id="StateA">
			<state id="StateA1">
				<transition event="200" target=":pseudostateChoice_57"/>
				<transition event="100" target="StateA2"/>
				<transition event="100" target="StateA3"/>
			</state>
			<choice id=":pseudostateChoice_57">
				<transition cond="001" target="StateA1"/>
				<transition cond="002" target="StateB"/>
			</choice>
			<state id="StateA2">
			</state>
			<state id="StateA3">
				<transition event="100" target=":pseudostateTerminate_58"/>
				<transition event="300" target="StateB"/>
			</state>
		</state>
		<state id="StateB">
			<transition event="300" target="StateA1"/>
			<transition event="200" target=":finalState_61"/>
			<transition event="100" target="StateA1"/>
		</state>
		<final id=":finalState_61"/>
		<final id=":pseudostateTerminate_58"/>
	</state>
</scxml>
